// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrEejAmvE_v5aX4a5NdKWU9W7NTh8r5Qc',
    appId: '1:562134379208:android:fe9b5bfc33a1d5ea4f93fd',
    messagingSenderId: '562134379208',
    projectId: 'doanchuyennganh-65edf',
    storageBucket: 'doanchuyennganh-65edf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsf9-DcOjEv2xFlpmPTqZ7WZHyxOMekzM',
    appId: '1:562134379208:ios:0a7056ec7d288fff4f93fd',
    messagingSenderId: '562134379208',
    projectId: 'doanchuyennganh-65edf',
    storageBucket: 'doanchuyennganh-65edf.firebasestorage.app',
    iosClientId: '562134379208-c13l73bfd9es5kg62eo9dh2ivvgqbjfl.apps.googleusercontent.com',
    iosBundleId: 'com.example.carRentalApp',
  );

}